[[element-codes]]
= Code lists for coded elements


.Code lists used in the Pre-award Catalogue transaction
[cols="2,1,3,3", options="header"]
|====
|Business Term
|schemeID or listID
|Applicable XPath
|Code list (link or subset values)

| Attachment description code
| UNCL1001
| cbc:DocumentTypeCode
a| link:https://www.unece.org/fileadmin/DAM/trade/untdid/d17a/tred/tred1001.htm[UN/CEFACT code list 1001, D.17A]

| Mime code of attached document
|
| cbc:EmbeddedDocumentBinaryObject[@mimeCode]
a| link:http://www.iana.org/assignments/media-types[IANA]

#Add version information?#


| Country code
| ISO3166-1:Alpha2
| cac:CountryCode/cbc:IdentificationCode
a| link:http://www.iso.org/iso/home/standards/country_codes.htm[ISO 3166-1]

| Hazardous item UNDG code
| UNCL8273
| cbc:UNDGCode
a| link:https://www.unece.org/fileadmin/DAM/trade/untdid/d17a/tred/tred8273.htm[UN/CEFACT code list 8273, D.17A]

| Contract type (procurement project identifier)
| UNCL1001
| cbc:ContractTypeCode
a| Subset of  link:https://www.unece.org/fileadmin/DAM/trade/untdid/d17a/tred/tred1001.htm[UN/CEFACT code list 1001, D.17A]
[horizontal]
311:: Request for quote

is the only allowed value

| Item price type
| UNCL5387
| cbc:PriceTypeCode
a| link:https://www.unece.org/fileadmin/DAM/trade/untdid/d17a/tred/tred5387.htm[UN/CEFACT code list 5387, D.17A]

| Orderable unit code
|
| cbc:*[@unitCode]
a| link:http://www.unece.org/tradewelcome/un-centre-for-trade-facilitation-and-e-businessuncefact/outputs/cefactrecommendationsrec-index/list-of-trade-facilitation-recommendations-n-16-to-20.html[UN/ECE Recommendation 20, Revision 8 (2012) ]

| Currency identifier
|
| cbc:*[@currencyID]
a| link:https://www.iso.org/iso-4217-currency-codes.html[ISO 4217:2015]

| Item VAT category code
| UNCL5305
| cac:ClassifiedTaxCategory/cbc:ID
a| Subset of link:https://www.unece.org/fileadmin/DAM/trade/untdid/d17a/tred/tred5305.htm[UN/CEFACT code list 5305]
[horizontal]
AE:: Vat Reverse Charge
E:: Exempt from Tax
S:: Standard rate
Z:: Zero rated goods
H:: Higher rate
AA:: Lower rate

|====
