[[benefits]]
= Benefits

PEPPOL BIS pre-award catalogue will stimulate the service provider marked to develop services that covers tendering processes both for CA´s and EO´s. Pre-award catalogue together with tendering metadata transaction (trdm090) and confirmation message (trdm045) will:

* make it possible for CA to evaluate products and services automatically through their tendering tools
* make it easier for the EOs to participate in different tendering processes.
* save time for the EO to offer their products and services to CA when the list of products and services are standardized
* save time for the CA to have a standardized list of products and services
*	make it possible for EO´s to use tools to pre-fill their information before the specific tender and send the offer in a structured way through CEF eDelivery (PEPPOL) infrastructure. The benefit is that EO use one tool in different tenders instead of dealing with different interfaces depending on which tool CA use.
* make it possible for the CA to use the pre-award catalogue in mini-competitions and re-opening of competitions
* make it possible for EO´s to use the PEPPOL BIS pre-award catalogue xml when up-loading the tender in a 3-corner model on condition that tendering systems are compatible.
